import "./globals.css"

import { type PropsWithChildren } from "react"
import type { Metadata } from "next"

import { WithNavbar } from "@/components/layouts/with-navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ja">
      <body>
        <WithNavbar>{children}</WithNavbar>
      </body>
    </html>
  )
}
