import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"

import { type PropsWithChildren } from "react"

import { cn } from "@/lib/utils"
import { Sidebar } from "@/components/layouts/sidebar"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ja">
      <body className={cn(inter.className, "container flex")}>
        <Sidebar className="hidden max-w-[240px] lg:block" />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  )
}
