import { Suspense } from "react"
import type { Metadata } from "next"
import { signOut as signOutByAuthJS } from "@/auth"
import { DEFAULT_LOGOUT_REDIRECT } from "@/routes"

import { Button } from "@/components/ui/button"
import { KeyIndicatorSkeleton } from "@/components/skeletons/key-indicator-skeleton"

import { ChannelStats } from "./_components/channel-stats"
import { KeyIndicator } from "./_components/key-indicator"

export const metadata: Metadata = {
  title: "分析画面",
  description: "Generated by create next app",
}

export default function AnalysisPage() {
  return (
    <div className="flex flex-col gap-10">
      <div className="flex items-center justify-between">
        <ChannelStats />
        <form
          action={async () => {
            "use server"

            await signOutByAuthJS({
              redirectTo: DEFAULT_LOGOUT_REDIRECT,
            })
          }}
        >
          <Button variant={"ghost"} type="submit">
            サインアウト
          </Button>
        </form>
      </div>
      <div className="flex flex-col gap-2">
        <div className="flex items-center justify-between">
          <p className="text-2xl font-bold">重要指標</p>
          <p className="text-sm text-muted-foreground">過去28日間</p>
        </div>
        <Suspense fallback={<KeyIndicatorSkeleton count={3} />}>
          <KeyIndicator />
        </Suspense>
      </div>
      <div>
        <p className="text-2xl font-bold">コメント返信状況</p>
      </div>
    </div>
  )
}
